# Generated by Django 3.2.4 on 2021-06-17 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_galeriaphotos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-id']},
        ),
    ]
