# Generated by Django 3.2.4 on 2021-06-18 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_post_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='categories',
            field=models.CharField(choices=[('Menino', 'Menino'), ('Menina', 'Menina')], default='Menino', max_length=6),
        ),
        migrations.AddField(
            model_name='post',
            name='referencia',
            field=models.CharField(default=1, max_length=100, verbose_name='Referencia'),
            preserve_default=False,
        ),
    ]
