# Generated by Django 3.2.4 on 2021-06-18 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20210618_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=models.CharField(blank=True, choices=[('Menino', 'Menino'), ('Menina', 'Menina')], default='Menino', max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='referencia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Referencia'),
        ),
    ]
