# Generated by Django 3.2.4 on 2021-06-23 07:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20210618_1342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='categories',
            new_name='sexo',
        ),
        migrations.RemoveField(
            model_name='post',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='post',
            name='vendas',
        ),
        migrations.AddField(
            model_name='post',
            name='stock_bebe',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock Bebé'),
        ),
        migrations.AddField(
            model_name='post',
            name='stock_crianca',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock Criança'),
        ),
        migrations.AddField(
            model_name='post',
            name='stock_junior',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock Junior'),
        ),
        migrations.AddField(
            model_name='post',
            name='vendas_bebe',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Vendas Bebé'),
        ),
        migrations.AddField(
            model_name='post',
            name='vendas_crianca',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Vendas Criança'),
        ),
        migrations.AddField(
            model_name='post',
            name='vendas_junior',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Vendas Junior'),
        ),
    ]
