# Generated by Django 3.2.4 on 2021-06-23 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20210623_0842'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='sexo',
            new_name='sexo_crianca',
        ),
    ]
