# Generated by Django 3.2.4 on 2021-06-23 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_rename_sexo_post_sexo_crianca'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='sexo_crianca',
            new_name='categories',
        ),
    ]
