# Generated by Django 3.2.4 on 2021-06-23 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_rename_sexo_crianca_post_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('telefone', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('message', models.TextField(default='mensagem')),
                ('artigo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='website.post')),
            ],
        ),
    ]
