# Generated by Django 3.2.4 on 2021-06-23 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='tratado',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='referencia',
            field=models.CharField(default=1, max_length=100, verbose_name='Referencia'),
            preserve_default=False,
        ),
    ]
