# Generated by Django 3.2.4 on 2021-06-23 10:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_alter_contact_tratado'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='data_contact',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data'),
        ),
    ]
