# Generated by Django 3.2.4 on 2021-08-09 10:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_alter_contact_artigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='stock_bebe',
        ),
        migrations.RemoveField(
            model_name='post',
            name='stock_crianca',
        ),
        migrations.RemoveField(
            model_name='post',
            name='stock_junior',
        ),
        migrations.RemoveField(
            model_name='post',
            name='vendas_bebe',
        ),
        migrations.RemoveField(
            model_name='post',
            name='vendas_crianca',
        ),
        migrations.RemoveField(
            model_name='post',
            name='vendas_junior',
        ),
        migrations.AddField(
            model_name='post',
            name='stock_3_meses',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock 3 meses 62 cm'),
        ),
        migrations.AddField(
            model_name='post',
            name='stock_6_meses',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock 6 meses 68 cm'),
        ),
        migrations.AddField(
            model_name='post',
            name='stock_9_meses',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock 9 meses 74 cm'),
        ),
        migrations.AddField(
            model_name='post',
            name='vendas_3_meses',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Vendas 3 meses 62 cm'),
        ),
        migrations.AddField(
            model_name='post',
            name='vendas_6_meses',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Vendas 6 meses 68 cm'),
        ),
        migrations.AddField(
            model_name='post',
            name='vendas_9_meses',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Vendas 9 meses 74 cm'),
        ),
        migrations.AlterField(
            model_name='post',
            name='imagem_post',
            field=models.ImageField(default=1, upload_to='post_img/%Y/%m/%d', verbose_name='Imagem De Perfil'),
            preserve_default=False,
        ),
    ]
