# Generated by Django 3.2.4 on 2021-08-09 11:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_auto_20210809_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='vendido_3_meses',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='nrº vendido'),
        ),
    ]
