# Generated by Django 3.2.4 on 2021-08-09 12:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_post_vendido_3_meses'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='stock_10_anos',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock 10 anos 140 cm'),
        ),
        migrations.AddField(
            model_name='post',
            name='stock_11_anos',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock 11 anos 146 cm'),
        ),
        migrations.AddField(
            model_name='post',
            name='stock_12_anos',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock 12 anos 152 cm'),
        ),
        migrations.AddField(
            model_name='post',
            name='stock_12_meses',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock 12 meses 80 cm'),
        ),
        migrations.AddField(
            model_name='post',
            name='stock_13_anos',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock 13 anos 158 cm'),
        ),
        migrations.AddField(
            model_name='post',
            name='stock_14_anos',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock 14 anos 164 cm'),
        ),
        migrations.AddField(
            model_name='post',
            name='stock_18_meses',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock 18 meses 86 cm'),
        ),
        migrations.AddField(
            model_name='post',
            name='stock_2_anos',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock 2 anos 92 cm'),
        ),
        migrations.AddField(
            model_name='post',
            name='stock_3_anos',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock 3 anos 98 cm'),
        ),
        migrations.AddField(
            model_name='post',
            name='stock_4_anos',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock 4 anos 104 cm'),
        ),
        migrations.AddField(
            model_name='post',
            name='stock_5_anos',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock 5 anos 110 cm'),
        ),
        migrations.AddField(
            model_name='post',
            name='stock_6_anos',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock 6 anos 116 cm'),
        ),
        migrations.AddField(
            model_name='post',
            name='stock_7_anos',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock 7 anos 122 cm'),
        ),
        migrations.AddField(
            model_name='post',
            name='stock_8_anos',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock 8 anos 128 cm'),
        ),
        migrations.AddField(
            model_name='post',
            name='stock_9_anos',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock 9 anos 134 cm'),
        ),
        migrations.AddField(
            model_name='post',
            name='vendas_10_anos',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='vendas 10 anos 140 cm'),
        ),
        migrations.AddField(
            model_name='post',
            name='vendas_11_anos',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='vendas 11 anos 146 cm'),
        ),
        migrations.AddField(
            model_name='post',
            name='vendas_12_anos',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='vendas 12 anos 152 cm'),
        ),
        migrations.AddField(
            model_name='post',
            name='vendas_12_meses',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='vendas 12 meses 80 cm'),
        ),
        migrations.AddField(
            model_name='post',
            name='vendas_13_anos',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='vendas 13 anos 158 cm'),
        ),
        migrations.AddField(
            model_name='post',
            name='vendas_14_anos',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='vendas 14 anos 164 cm'),
        ),
        migrations.AddField(
            model_name='post',
            name='vendas_18_meses',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='vendas 18 meses 86 cm'),
        ),
        migrations.AddField(
            model_name='post',
            name='vendas_2_anos',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='vendas 2 anos 92 cm'),
        ),
        migrations.AddField(
            model_name='post',
            name='vendas_3_anos',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='vendas 3 anos 98 cm'),
        ),
        migrations.AddField(
            model_name='post',
            name='vendas_4_anos',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='vendas 4 anos 104 cm'),
        ),
        migrations.AddField(
            model_name='post',
            name='vendas_5_anos',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='vendas 5 anos 110 cm'),
        ),
        migrations.AddField(
            model_name='post',
            name='vendas_6_anos',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='vendas 6 anos 116 cm'),
        ),
        migrations.AddField(
            model_name='post',
            name='vendas_7_anos',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='vendas 7 anos 122 cm'),
        ),
        migrations.AddField(
            model_name='post',
            name='vendas_8_anos',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='vendas 8 anos 128 cm'),
        ),
        migrations.AddField(
            model_name='post',
            name='vendas_9_anos',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='vendas 9 anos 134 cm'),
        ),
        migrations.AddField(
            model_name='post',
            name='vendido_10_anos',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='nrº vendido'),
        ),
        migrations.AddField(
            model_name='post',
            name='vendido_11_anos',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='nrº vendido'),
        ),
        migrations.AddField(
            model_name='post',
            name='vendido_12_anos',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='nrº vendido'),
        ),
        migrations.AddField(
            model_name='post',
            name='vendido_12_meses',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='nrº vendido'),
        ),
        migrations.AddField(
            model_name='post',
            name='vendido_13_anos',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='nrº vendido'),
        ),
        migrations.AddField(
            model_name='post',
            name='vendido_14_anos',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='nrº vendido'),
        ),
        migrations.AddField(
            model_name='post',
            name='vendido_18_meses',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='nrº vendido'),
        ),
        migrations.AddField(
            model_name='post',
            name='vendido_2_anos',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='nrº vendido'),
        ),
        migrations.AddField(
            model_name='post',
            name='vendido_3_anos',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='nrº vendido'),
        ),
        migrations.AddField(
            model_name='post',
            name='vendido_4_anos',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='nrº vendido'),
        ),
        migrations.AddField(
            model_name='post',
            name='vendido_5_anos',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='nrº vendido'),
        ),
        migrations.AddField(
            model_name='post',
            name='vendido_6_anos',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='nrº vendido'),
        ),
        migrations.AddField(
            model_name='post',
            name='vendido_6_meses',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='nrº vendido'),
        ),
        migrations.AddField(
            model_name='post',
            name='vendido_7_anos',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='nrº vendido'),
        ),
        migrations.AddField(
            model_name='post',
            name='vendido_8_anos',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='nrº vendido'),
        ),
        migrations.AddField(
            model_name='post',
            name='vendido_9_anos',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='nrº vendido'),
        ),
        migrations.AddField(
            model_name='post',
            name='vendido_9_meses',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='nrº vendido'),
        ),
    ]
