# Generated by Django 3.2.4 on 2021-08-09 19:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_auto_20210809_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='stock_10_11_anos',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='stock 10/11 anos 170cm'),
        ),
        migrations.AddField(
            model_name='post',
            name='stock_2_3_anos',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='stock 2/3 anos 90cm'),
        ),
        migrations.AddField(
            model_name='post',
            name='stock_3_4_anos',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='stock 3/4 anos 100cm'),
        ),
        migrations.AddField(
            model_name='post',
            name='stock_4_5_anos',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='stock 4/5 anos 110cm'),
        ),
        migrations.AddField(
            model_name='post',
            name='stock_5_6_anos',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='stock 5/6 anos 120cm'),
        ),
        migrations.AddField(
            model_name='post',
            name='stock_6_7_anos',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='stock 6/7 anos 130cm'),
        ),
        migrations.AddField(
            model_name='post',
            name='stock_7_8_anos',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='stock 7/8 anos 140cm'),
        ),
        migrations.AddField(
            model_name='post',
            name='stock_8_9_anos',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='stock 8/9 anos 150cm'),
        ),
        migrations.AddField(
            model_name='post',
            name='stock_9_10_anos',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='stock 9/10 anos 160cm'),
        ),
        migrations.AddField(
            model_name='post',
            name='vendas_10_11_anos',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='vendas 10/11 anos 170cm'),
        ),
        migrations.AddField(
            model_name='post',
            name='vendas_2_3_anos',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='vendas 2/3 anos 90cm'),
        ),
        migrations.AddField(
            model_name='post',
            name='vendas_3_4_anos',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='vendas 3/4 anos 100cm'),
        ),
        migrations.AddField(
            model_name='post',
            name='vendas_4_5_anos',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='vendas 4/5 anos 110cm'),
        ),
        migrations.AddField(
            model_name='post',
            name='vendas_5_6_anos',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='vendas 5/6 anos 120cm'),
        ),
        migrations.AddField(
            model_name='post',
            name='vendas_6_7_anos',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='vendas 6/7 anos 130cm'),
        ),
        migrations.AddField(
            model_name='post',
            name='vendas_7_8_anos',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='vendas 7/8 anos 140cm'),
        ),
        migrations.AddField(
            model_name='post',
            name='vendas_8_9_anos',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='vendas 8/9 anos 150cm'),
        ),
        migrations.AddField(
            model_name='post',
            name='vendas_9_10_anos',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='vendas 9/10 anos 160cm'),
        ),
        migrations.AddField(
            model_name='post',
            name='vendido_10_11_anos',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='nrº vendido'),
        ),
        migrations.AddField(
            model_name='post',
            name='vendido_2_3_anos',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='nrº vendido'),
        ),
        migrations.AddField(
            model_name='post',
            name='vendido_3_4_anos',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='nrº vendido'),
        ),
        migrations.AddField(
            model_name='post',
            name='vendido_4_5_anos',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='nrº vendido'),
        ),
        migrations.AddField(
            model_name='post',
            name='vendido_5_6_anos',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='nrº vendido'),
        ),
        migrations.AddField(
            model_name='post',
            name='vendido_6_7_anos',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='nrº vendido'),
        ),
        migrations.AddField(
            model_name='post',
            name='vendido_7_8_anos',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='nrº vendido'),
        ),
        migrations.AddField(
            model_name='post',
            name='vendido_8_9_anos',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='nrº vendido'),
        ),
        migrations.AddField(
            model_name='post',
            name='vendido_9_10_anos',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='nrº vendido'),
        ),
    ]
