# Generated by Django 3.2.4 on 2021-08-10 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_auto_20210809_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tamanho',
            field=models.CharField(choices=[('China', 'China'), ('polonia', 'Polonia')], default='polonia', max_length=10),
        ),
    ]
